export const SESSION_ACTIVE_WINDOW_HOURS = 5;
export const SESSION_RETENTION_DAYS = 2;
export const SESSION_AUTO_PURGE_DAYS = 4;
export const CONTEXT_MAX_FILE_SIZE_KB = 500;
export const ARCHIVE_RETENTION_DAYS = 30;
export const LEARNED_PATTERNS_MAX_ENTRIES = 200;
