import { CommandArgs, CommandHandler, CommandResult } from '../../types/commandTypes.js';
import { CommandName } from '../../enums/commandEnum.js';
import { GitService } from '../../services/gitService.js';
import { GitHubService } from '../../services/githubService.js';
import { config } from '../../config/index.js';
import { createChildLogger } from '../../logger/index.js';
import { CREATE_PR_COMMAND_DESCRIPTION } from '../../constants/commandConstants.js';
import { branchSlug, requireGitHubConfig, toErrorResult } from './prHandlerUtil.js';

const log = createChildLogger('createPrHandler');

/**
 * Handles `@CREATE_PR <description>`.
 *
 * Commits the current workspace changes onto a fresh branch, pushes it, and
 * opens a GitHub pull request. The description text becomes the PR title/body.
 */
export class CreatePrHandler implements CommandHandler {
  public readonly name: CommandName = CommandName.CREATE_PR;
  public readonly description: string = CREATE_PR_COMMAND_DESCRIPTION;

  // Services are constructed lazily AFTER the config guard — GitHubService
  // throws at construction when GitHub is unconfigured (which would crash boot
  // if instantiated eagerly here). Overrides are injectable for tests.
  public constructor(
    private readonly gitOverride?: GitService,
    private readonly githubOverride?: GitHubService,
  ) {}

  public async execute(args: CommandArgs, sessionId: string): Promise<CommandResult> {
    const configError = requireGitHubConfig();
    if (configError) return configError;

    const git = this.gitOverride ?? new GitService();
    const github = this.githubOverride ?? new GitHubService();

    const description = ((args.requirement as string | undefined) ?? '').trim();
    const title = description ? firstLine(description) : 'NeuroStack: automated changes';
    const base = config.github.defaultBranch;
    const branch = `neurostack/${branchSlug(description)}-${Date.now().toString(36)}`;

    log.info('Executing CREATE_PR handler', { source: 'createPrHandler#execute', sessionId, branch, base });

    try {
      await git.createBranch(branch);
      await git.stageFiles();
      await git.commitChanges(title);
      await git.pushBranch(branch);

      const body = [
        description || 'Automated changes generated by NeuroStack.',
        '',
        '---',
        '🤖 Opened by NeuroStack',
      ].join('\n');
      const pr = await github.createPullRequest(title, branch, base, body);

      log.info('PR created', { source: 'createPrHandler#execute', prNumber: pr.number, branch });
      return {
        success: true,
        message: [
          `## ✅ Pull request #${pr.number} created`,
          '',
          `**Title:** ${title}`,
          `**Branch:** \`${branch}\` → \`${base}\``,
          `**URL:** ${pr.url}`,
          '',
          `Review it with \`@PR_REVIEW #${pr.number}\`, then merge with \`@MERGE_PR #${pr.number}\`.`,
        ].join('\n'),
        data: { prNumber: pr.number, prUrl: pr.url, branch },
      };
    } catch (error: unknown) {
      log.error('CREATE_PR failed', {
        source: 'createPrHandler#execute',
        error: error instanceof Error ? error.message : String(error),
      });
      return toErrorResult('Create PR', error);
    }
  }
}

function firstLine(text: string): string {
  const line = text.split(/\r?\n/).find((l) => l.trim()) ?? text;
  return line.length > 72 ? `${line.slice(0, 69)}...` : line;
}
